export const muiComponents = `const { 
    Accordion, AccordionActions, AccordionDetails, AccordionSummary, Alert, AlertTitle, AppBar, Autocomplete, Avatar, 
    AvatarGroup, Backdrop, Badge, BottomNavigation, BottomNavigationAction, Box, Breadcrumbs, Button, ButtonBase, 
    ButtonGroup, ButtonGroupButtonContext, ButtonGroupContext, Card, CardActionArea, CardActions, CardContent, 
    CardHeader, CardMedia, Checkbox, Chip, CircularProgress, ClickAwayListener, Collapse, Container, CssBaseline, 
    Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Divider, Drawer, Experimental_CssVarsProvider, 
    Fab, Fade, FilledInput, FormControl, FormControlLabel, FormGroup, FormHelperText, FormLabel, FormLabelRoot, 
    GlobalStyles, Grid, Grow, Hidden, Icon, IconButton, ImageList, ImageListItem, ImageListItemBar, Input, InputAdornment, 
    InputBase, InputLabel, LinearProgress, Link, List, ListItem, ListItemAvatar, ListItemButton, ListItemIcon, 
    ListItemSecondaryAction, ListItemText, ListSubheader, Menu, MenuItem, MenuList, MobileStepper, Modal, ModalManager, 
    NativeSelect, NoSsr, OutlinedInput, Pagination, PaginationItem, Paper, Popover, PopoverPaper, PopoverRoot, Popper, 
    Portal, Radio, RadioGroup, Rating, ScopedCssBaseline, Select, Skeleton, Slide, Slider, SliderMark, SliderMarkLabel, 
    SliderRail, SliderRoot, SliderThumb, SliderTrack, SliderValueLabel, Snackbar, SnackbarContent, SpeedDial, 
    SpeedDialAction, SpeedDialIcon, Stack, Step, StepButton, StepConnector, StepContent, StepContext, StepIcon, StepLabel, 
    Stepper, StepperContext, StyledEngineProvider, SvgIcon, SwipeableDrawer, Switch, Tab, TabScrollButton, Table, 
    TableBody, TableCell, TableContainer, TableFooter, TableHead, TablePagination, TableRow, TableSortLabel, Tabs, 
    TextField, TextareaAutosize, ThemeProvider, ToggleButton, ToggleButtonGroup, Toolbar, Tooltip, Typography, 
    Unstable_Grid2, Unstable_TrapFocus, Zoom, accordionActionsClasses, accordionClasses, accordionDetailsClasses, 
    accordionSummaryClasses, adaptV4Theme, alertClasses, alertTitleClasses, alpha, appBarClasses, autocompleteClasses, 
    avatarClasses, avatarGroupClasses, backdropClasses, badgeClasses, bottomNavigationActionClasses, bottomNavigationClasses, 
    boxClasses, breadcrumbsClasses, buttonBaseClasses, buttonClasses, buttonGroupClasses, capitalize, cardActionAreaClasses, 
    cardActionsClasses, cardClasses, cardContentClasses, cardHeaderClasses, cardMediaClasses, checkboxClasses, chipClasses, 
    circularProgressClasses, collapseClasses, colors, containerClasses, createChainedFunction, createFilterOptions, 
    createMuiTheme, createStyles, createSvgIcon, createTheme, css, darkScrollbar, darken, debounce, decomposeColor, 
    deprecatedPropType, dialogActionsClasses, dialogClasses, dialogContentClasses, dialogContentTextClasses, dialogTitleClasses, 
    dividerClasses, drawerClasses, duration, easing, emphasize, experimentalStyled, experimental_extendTheme, experimental_sx, 
    fabClasses, filledInputClasses, formControlClasses, formControlLabelClasses, formGroupClasses, formHelperTextClasses, 
    formLabelClasses, generateUtilityClass, generateUtilityClasses, getAccordionActionsUtilityClass, getAccordionDetailsUtilityClass, 
    getAccordionSummaryUtilityClass, getAccordionUtilityClass, getAlertTitleUtilityClass, getAlertUtilityClass, 
    getAppBarUtilityClass, getAutocompleteUtilityClass, getAvatarGroupUtilityClass, getAvatarUtilityClass, 
    getBackdropUtilityClass, getBadgeUtilityClass, getBottomNavigationActionUtilityClass, getBottomNavigationUtilityClass, 
    getBreadcrumbsUtilityClass, getButtonBaseUtilityClass, getButtonGroupUtilityClass, getButtonUtilityClass, 
    getCardActionAreaUtilityClass, getCardActionsUtilityClass, getCardContentUtilityClass, getCardHeaderUtilityClass, 
    getCardMediaUtilityClass, getCardUtilityClass, getCheckboxUtilityClass, getChipUtilityClass, 
    getCircularProgressUtilityClass, getCollapseUtilityClass, getContainerUtilityClass, getContrastRatio, 
    getDialogActionsUtilityClass, getDialogContentTextUtilityClass, getDialogContentUtilityClass, getDialogTitleUtilityClass, 
    getDialogUtilityClass, getDividerUtilityClass, getDrawerUtilityClass, getFabUtilityClass, getFilledInputUtilityClass, 
    getFormControlLabelUtilityClasses, getFormControlUtilityClasses, getFormGroupUtilityClass, getFormHelperTextUtilityClasses, 
    getFormLabelUtilityClasses, getGrid2UtilityClass, getGridUtilityClass, getIconButtonUtilityClass, getIconUtilityClass, 
    getImageListItemBarUtilityClass, getImageListItemUtilityClass, getImageListUtilityClass, getInitColorSchemeScript, 
    getInputAdornmentUtilityClass, getInputBaseUtilityClass, getInputLabelUtilityClasses, getInputUtilityClass, 
    getLinearProgressUtilityClass, getLinkUtilityClass, getListItemAvatarUtilityClass, getListItemButtonUtilityClass, 
    getListItemIconUtilityClass, getListItemSecondaryActionClassesUtilityClass, getListItemTextUtilityClass, 
    getListItemUtilityClass, getListSubheaderUtilityClass, getListUtilityClass, getLuminance, getMenuItemUtilityClass, 
    getMenuUtilityClass, getMobileStepperUtilityClass, getModalUtilityClass, getNativeSelectUtilityClasses, getOffsetLeft, 
    getOffsetTop, getOutlinedInputUtilityClass, getOverlayAlpha, getPaginationItemUtilityClass, getPaginationUtilityClass, 
    getPaperUtilityClass, getPopoverUtilityClass, getPopperUtilityClass, getPortalUtilityClass, getRadioUtilityClass, 
    getRatingUtilityClass, getScopedCssBaselineUtilityClass, getSelectUtilityClass, getSkeletonUtilityClass, 
    getSlideUtilityClass, getSliderUtilityClass, getSnackbarContentUtilityClass, getSnackbarUtilityClass, getSpeedDialActionUtilityClass, 
    getSpeedDialIconUtilityClass, getSpeedDialUtilityClass, getStepButtonUtilityClass, getStepConnectorUtilityClass, 
    getStepContentUtilityClass, getStepIconUtilityClass, getStepLabelUtilityClass, getStepUtilityClass, getStepperUtilityClass, 
    getSvgIconUtilityClass, getSwipeableDrawerUtilityClass, getSwitchUtilityClass, getTabScrollButtonUtilityClass, 
    getTabUtilityClass, getTableBodyUtilityClass, getTableCellUtilityClass, getTableContainerUtilityClass, 
    getTableFooterUtilityClass, getTableHeadUtilityClass, getTablePaginationUtilityClass, getTableRowUtilityClass, 
    getTableSortLabelUtilityClass, getTabsUtilityClass, getTextFieldUtilityClass, getTextareaAutosizeUtilityClass, 
    getToggleButtonGroupUtilityClass, getToggleButtonUtilityClass, getToolbarUtilityClass, getTooltipUtilityClass, 
    getTypographyUtilityClass, getUnstable_Grid2UtilityClass, getUnstable_TrapFocusUtilityClass, getZoomUtilityClass 
  } = MaterialUI;`;
